// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rental.Models;

namespace Rental.Migrations
{
    [DbContext(typeof(RentalDbContext))]
    partial class RentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("Rental.Models.ItemModels.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<DateTime>("ExpireTime");

                    b.Property<DateTime>("PostTime");

                    b.Property<int>("Price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("ItemID");

                    b.ToTable("items");

                    b.HasData(
                        new { ItemID = 1, Detail = "details1", ExpireTime = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), PostTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Price = 200, Title = "item1" },
                        new { ItemID = 2, Detail = "details2", ExpireTime = new DateTime(2020, 7, 1, 6, 0, 0, 0, DateTimeKind.Unspecified), PostTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Price = 100, Title = "item2" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
